// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop.proto

package com.jackgallaher.smartlaptop;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.Empty)
    com.google.protobuf.MessageOrBuilder {
}
