// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop.proto

package com.jackgallaher.smartlaptop;

public interface PowerStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.PowerStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();

  /**
   * <code>string statusMsg = 2;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();

  /**
   * <code>int32 batterylife = 3;</code>
   */
  int getBatterylife();
}
