// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laptop.proto

package com.jackgallaher.smartlaptop;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();
}
