// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pda.proto

package com.jackgallaher.smartpda;

public interface AppointmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.Appointment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string note = 2;</code>
   */
  java.lang.String getNote();
  /**
   * <code>string note = 2;</code>
   */
  com.google.protobuf.ByteString
      getNoteBytes();

  /**
   * <code>string time = 3;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string date = 4;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 4;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
