// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pda.proto

package com.jackgallaher.smartpda;

public interface DateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.Date)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
