// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pda.proto

package com.jackgallaher.smartpda;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.Empty)
    com.google.protobuf.MessageOrBuilder {
}
