// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pda.proto

package com.jackgallaher.smartpda;

public interface PlayableFilesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.PlayableFiles)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1;</code>
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
