// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pda.proto

package com.jackgallaher.smartpda;

public interface ToDoListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.ToDoList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string day = 1;</code>
   */
  java.lang.String getDay();
  /**
   * <code>string day = 1;</code>
   */
  com.google.protobuf.ByteString
      getDayBytes();

  /**
   * <code>string todo = 2;</code>
   */
  java.lang.String getTodo();
  /**
   * <code>string todo = 2;</code>
   */
  com.google.protobuf.ByteString
      getTodoBytes();
}
