// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pda.proto

package com.jackgallaher.smartpda;

public interface TypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.Type)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
