// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projector.proto

package com.jackgallaher.smartprojector;

public final class SmartDeviceProjectorImpl {
  private SmartDeviceProjectorImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartdevice_PowerStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartdevice_PowerStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartdevice_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartdevice_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017projector.proto\022\013smartdevice\032\033google/p" +
      "rotobuf/empty.proto\"\035\n\013PowerStatus\022\016\n\006st" +
      "atus\030\001 \001(\010\"\030\n\010Response\022\014\n\004text\030\001 \001(\t2\214\002\n" +
      "\016smartProjector\022>\n\010switchOn\022\026.google.pro" +
      "tobuf.Empty\032\030.smartdevice.PowerStatus\"\000\022" +
      "?\n\tswitchOff\022\026.google.protobuf.Empty\032\030.s" +
      "martdevice.PowerStatus\"\000\022<\n\tinputHDMI\022\026." +
      "google.protobuf.Empty\032\025.smartdevice.Resp" +
      "onse\"\000\022;\n\010inputVGA\022\026.google.protobuf.Emp" +
      "ty\032\025.smartdevice.Response\"\000B=\n\037com.jackg" +
      "allaher.smartprojectorB\030SmartDeviceProje" +
      "ctorImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_smartdevice_PowerStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartdevice_PowerStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartdevice_PowerStatus_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_smartdevice_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartdevice_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartdevice_Response_descriptor,
        new java.lang.String[] { "Text", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
