// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package com.jackgallaher.smartdevice;

public interface ContactsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.Contacts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string number = 2;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 2;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>string network = 3;</code>
   */
  java.lang.String getNetwork();
  /**
   * <code>string network = 3;</code>
   */
  com.google.protobuf.ByteString
      getNetworkBytes();
}
