// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package com.jackgallaher.smartdevice;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.Empty)
    com.google.protobuf.MessageOrBuilder {
}
