// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package com.jackgallaher.smartdevice;

public interface PowerStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartdevice.PowerStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();
}
